import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import StyledComponentsRegistry from '@/lib/StyledComponentsRegistry';
import StoreProvider from '@/lib/StoreProvider';
import React from 'react';
import TanstackQueryProvider from '@/lib/TanstackQueryProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Maru',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <TanstackQueryProvider>
          <StoreProvider>
            <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
          </StoreProvider>
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
