# This is a basic workflow to help you get started with Actions

name: Trigger Push Event

# Controls when the workflow will run
on:
  push:
      branches:
        - main
        - dev
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  trigger:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Notify Push Event
        env:
          TARGET_REPO: capstone-maru/maru
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.PAT }}" \
            -d '{"event_type": "${{ vars.ACTION_TYPE }}"}' \
            https://api.github.com/repos/${{ env.TARGET_REPO }}/dispatches
